import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import WhyKaya from '../components/Landing/WhyKaya'
import KayaCapital from '../components/Landing/KayaCapital'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <WhyKaya />
        <KayaCapital />
      </div>
      <p>here too</p>
    </div>
  )
}
